language:
    - python

python:
    - 3.3
    - 3.4
    - 3.5
    - 3.5-dev
    - nightly

env:
    - CROSSLINKING_CONFIG=crosslinking_bot/.crosslinking_config.yaml

before_install:
    - openssl aes-256-cbc -K $encrypted_c0b0de524ab9_key -iv $encrypted_c0b0de524ab9_iv
      -in .crosslinking_config.yaml.enc -out .crosslinking_config.yaml -d

install:
    - pip3 install .

script:
    - py.test

